/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.cnscud.xpower.ddd.schema;



public enum Type implements org.apache.thrift.TEnum {
  CLUSTER(1),
  ROUTE(2);

  private final int value;

  private Type(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static Type findByValue(int value) { 
    switch (value) {
      case 1:
        return CLUSTER;
      case 2:
        return ROUTE;
      default:
        return null;
    }
  }
}
