/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.cnscud.xpower.cache.schema;


public enum CacheType implements org.apache.thrift.TEnum {
  REDIS(1),
  MEMCACHE(2),
  EHCACHE(3);

  private final int value;

  private CacheType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static CacheType findByValue(int value) { 
    switch (value) {
      case 1:
        return REDIS;
      case 2:
        return MEMCACHE;
      case 3:
        return EHCACHE;
      default:
        return null;
    }
  }
}
